feat(ci/license-check): check if specifed images have been manually l… (#1203)
…icense checked

Also fixed title of job.

This will fix the problem with trivy, that the licenses of the software
in an docker-image are ok, and not if the docker-image itself is ok.

The list will contain every image used by us and check, if an image used
by us is not in this list.

---------

Co-authored-by: Chris Werner Rau <cwr@teuto.net>

diff --git a/.github/workflows/check-licenses.yaml b/.github/workflows/check-licenses.yaml
--- a/.github/workflows/check-licenses.yaml
+++ b/.github/workflows/check-licenses.yaml
@@ -1,4 +1,4 @@
-name: Lint Helm Charts
+name: Check used licenses
 
 on:
   pull_request:
@@ -23,3 +23,19 @@ jobs:
       - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
       - run: pip install yq
       - run: ./.github/scripts/scan-for-licenses.sh ${{ needs.getChangedChart.outputs.chart }}
+  check-licenses-list:
+    name: check licenses from list
+    runs-on: ubuntu-latest
+    needs: getChangedChart
+    steps:
+      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
+      - run: pip install yq
+      - env:
+          chart: ${{ needs.getChangedChart.outputs.chart }}
+        run: |
+          # shellcheck disable=SC2016
+          if missingImages="$(yq -r -e -c --argjson usedImages "$(cat "${chart?}/Chart.yaml" .github/image_licenses.yaml | yq -r '.annotations["artifacthub.io/images"]' | yq -r -c 'map(.image | split(":")[0]) | unique')" '$usedImages - (.licenses | keys) | if length == 0 then false else . end')"; then
+            echo "The following images have no license, please review:"
+            echo "$missingImages" | yq -r 'map("  - " + .)[]'
+            exit 1
+          fi
