fix(ci): just wait for job completion and then check for no failures
Before this a job could fail and would've just flown under the radar

diff --git a/.github/workflows/wait-for-checks.yaml b/.github/workflows/wait-for-checks.yaml
--- a/.github/workflows/wait-for-checks.yaml
+++ b/.github/workflows/wait-for-checks.yaml
@@ -28,8 +28,12 @@ jobs:
           set -e
           set -o pipefail
 
-          while unfinished_jobs="$(gh api --paginate "/repos/${GITHUB_REPOSITORY}/commits/${CHANGE_SHA}/check-runs" | jq --arg ignored "$IGNORED_JOBS,$CURRENT_JOB" -e '.check_runs | map(select(([.conclusion] | inside(["success","skipped","cancelled"]) | not) and ([.name] | inside($ignored | split(",")) | not))) | map("\(.name) (\(.conclusion // .status))") | if length == 0 then halt_error(1) end')"; do
-            echo "The following jobs are not (successfully) finished yet:" >&2
+          while unfinished_jobs="$(gh api --paginate "/repos/${GITHUB_REPOSITORY}/commits/${CHANGE_SHA}/check-runs" | jq --arg ignored "$IGNORED_JOBS,$CURRENT_JOB" -e '.check_runs | map(select((.status == "in_progress") and ([.name] | inside($ignored | split(",")) | not))) | map("\(.name) (\(.conclusion // .status))") | if length == 0 then halt_error(1) end')"; do
+            echo "The following jobs are not finished yet:" >&2
             echo "$unfinished_jobs" >&2
             sleep 5
           done
+          if ! gh api --paginate "/repos/${GITHUB_REPOSITORY}/commits/${CHANGE_SHA}/check-runs" | jq --arg ignored "$IGNORED_JOBS,$CURRENT_JOB" -e '.check_runs | map(select((.conclusion == "failure") and ([.name] | inside($ignored | split(",")) | not))) | length == 0'; then
+            echo "Some jobs have failed" >&2
+            exit 1
+          fi
